name: ssurade_application

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  injectable: ^2.5.0
  get_it: ^8.0.3
  copy_with_extension: ^6.0.0
  mutex: ^3.1.0
  dart_scope_functions: ^1.0.0
  bloc: ^8.1.4

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  auto_exporter: ^3.4.1
  injectable_generator: ^2.6.2
  copy_with_extension_gen: ^6.0.0
