name: ssurade_application

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  injectable: ^2.4.4
  get_it: ^7.7.0
  copy_with_extension: ^5.0.4
  mutex: ^3.1.0
  dart_scope_functions: ^0.1.8
  bloc: ^8.1.4

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  auto_exporter: ^3.4.1
  injectable_generator: ^2.6.2
  copy_with_extension_gen: ^5.0.4
