name: ssurade_adaptor

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ssurade_application:
    path: ../application

  parallel_worker:
    path: ../parallel_worker

  injectable: ^2.5.0
  get_it: ^7.7.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  dart_scope_functions: ^0.1.8
  http: ^1.2.2
  flutter_inappwebview: ^6.1.5
  sentry_flutter: ^8.9.0
  html: ^0.15.5
  df: ^0.4.0-nullsafety.0
  flutter_local_notifications: ^17.2.4
  fluttertoast: ^8.2.8
  package_info_plus: ^8.1.0
  version: ^3.0.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  image_gallery_saver:
    git:
      url: https://github.com/nnnlog/image_gallery_saver
      ref: 25c830a93561e5f89e01fe93b942cb88452caa4f
  flutter_exit_app: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.13
  auto_exporter: ^3.4.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
